apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: {{ .Values.appName }}
spec: 
  replicas: 1
  selector: 
    matchLabels:  
      app: {{ .Values.appName }}
  template:
    metadata:
      labels: 
        app: {{ .Values.appName }}
    spec: 
      containers: 
      - name: {{ .Values.containers.name }}
        image: "{{ .Values.containers.image }}:{{ .Values.containers.tag }}"
        imagePullPolicy: Never
        ports: 
          - containerPort: {{ .Values.ports.port }}
     
       

    